### ISSUE TITLE
Boss' drop displayed in loop

### ISSUE THREAD

**Issue by Xhell96** [wchill/steamSummerMinigame#112]
Your script recently got the same bug as the SteamDB one, the message with the boss' drops keep reappearing and stacking with the new loots.

**Comment by wchill** [comment]
Yeah, I'm aware of this bug. We're working on it

**Comment by welwood08** [comment]
Are we sure this was caused by scripts? Do we have a regression window? Did both scripts start exhibiting the problem at the same time?

I tried digging into it just now and my conclusion was the data was being repeated (and stacked with new loot) in responses from the server. This is feasible if some process for dealing with loot on the server side is slow. I shall continue investigating anyway.

**Comment by Xhell96** [comment]
For me SteamDB was doing it one day before wchill, and not excatly the same way. SteamDB just stack notification until the page is reloaded, wchill don't always loop and is cleared sometimes. Maybe it has something to do with the game's tab being in background.
