### ISSUE TITLE
[Suggestion] Auto-upgrade

### ISSUE THREAD

**Issue by Zazcallabah** [wchill/steamSummerMinigame#123]
I don't think the script currently does this. Should it? I'm tempted to say yes, especially if there is a way to turn it off. Is anyone working on it currently? I'm tempted to start working on it myself, but it's almost midnight and I have work in the morning.

**Comment by wchill** [comment]
A lot of people have asked for this, and while there exist working implementations of this in various forms, the game is still changing very quickly so auto-upgrade is something I feel is not a huge priority right now.

I do intend on eventually adding it in, but there's some other things that will take priority.

**Comment by corymcdonough** [comment]
The auto-upgrade scripts are still being optimized. If you're not completely AFK'ing you can probably do a better job upgrading things yourself.

**Comment by Zazcallabah** [comment]
I see two use cases. One where you enter a new game and want to quickly get your dps up to par while spamming treasures or whatever you grabbed for your bp. That whole process could probably be automated in some way, since its just a long list of static abilities to get.

The second case is as you mention, for afk. Like when I leave my browser open overnight and want to auto buy 'new mouse button' whenever it can be afforded.

The latter case is probably the easiest to implement and also the most useful one?

**Comment by Zazcallabah** [comment]
I'm gonna try this out overnight I think.

    setInterval(function(){
      $J('.link').each(function() {
        if ($J(this).data('type') === 25 && !test.parentNode.parentNode.classList.contains("cantafford") ) {
          g_Minigame.CurrentScene().TryUpgrade(this);
          return false;
       } 
     });
    }, 10000 );

**Comment by Xhell96** [comment]
Also if you could auto buy the first Auto-fire Cannon it would allow to remove this natsy giant 'Buy at least 1 "Auto-fire Cannon" for lane switching to work.' from the main page and probably help script-begginers.

**Comment by luanmuniz** [comment]
The Big problem is the order which we will make the purchase. 
Its not just update if you can, we should do in an optimal order.

Any suggestions? 

By the way i will send a PR for this issue https://github.com/SteamDatabase/steamSummerMinigame/issues/105 in a few hours. We should use it as base for the order decision

**Comment by StaplerGuy** [comment]
The order seems like a simple optimization problem - especially given that the only upgrades added today are just 10x the older upgrades, with prices to match, right? Has it not already been solved in the autobuy code in one of the other scripts?

**Comment by meishuu** [comment]
I'm pretty sure [my approach](https://gist.github.com/meishuu/f83ee1de2992d5fc656c) does this as best as possible, under the assumption that gold income is not significantly tied to your own damage (i.e., always held constant).

Someone PM'd me to integrate mine with this somehow, so I'm just checking in to see if you guys would like that too or otherwise generate discussion on how I might do things better.

**Comment by TehNinth** [comment]
@StaplerGuy no, that's not how it works. Each time you buy, the price multiplies by 2.2, so it's not simply x10, it's a sum of a geometric series.

**Comment by StaplerGuy** [comment]
I don't see why the cost increase multiplier matters? Honestly, since the effects are constant, my mentioning 10x at all wasn't relevant.

At any given point, can't you just look at the most cost-effective in each category (auto click/manual click/elemental damage/crit damage), compare the four for dps/cost, buy that, and iterate? Is there some reason the script can't do it one at a time?

I like @meishuu's solution, although I think the elemental weights should be [0.4, 0.2, 0.2, 0.2] - assuming the 0.4 is roughly empirical, the other three seem irrelevant since a single element is superior, and I wouldn't want the 0.3 messing up an upgrade tree.

**Comment by meishuu** [comment]
>assuming the 0.4 is roughly empirical

It's not. I'd like to collect a ton of stats (verify crit_percentage and see exactly how often you spend time in lanes with your primary element) but I haven't been able to get into a scripting room lately.

**Comment by TehNinth** [comment]
Say each time you buy the price doubles, and a +1 is $1 and a +10 is $10:
Getting +10's worth in +1s will cost: 1+2+4+8+16+32+64+128+256+512 totalling 1023
Getting +10's worth in +1s will cost: 10 totalling 10
This means that you should only buy 10 in +1s when the price of buying a single 10 becomes more than 1023, which will happen after you buy 7 of them.
So your priority will be to buy 7 +10s before you even start buying any more +1s.
This is called the sum of a geometric series.

By using this logic and the actual game numbers, I have figured out the list of click upgrade things you need to buy in order to maximise efficiency: http://pastebin.com/h9DCnkLh
I used this badly written script to make that output past line 2: http://pastebin.com/vkHqYDBg

**Comment by StaplerGuy** [comment]
But once you buy the first +10, your choices are +1 for $1 or +10 for $20. For that specific purchase, the 1 is more efficient. In fact, if the multiplicative factor is fixed, you'll end up always wanting to keep the numbers owned of each type equal.

The only wrinkle is that high is more expensive, but also gives more DPS. I think it's a reasonable simplifying assumption that your individual DPS is basically zero relative to the room, so taking a small step rather than a large one doesn't actively hinder total progress, but that's down to taste, and I'd be fine with resolving ties in favor the more expensive item.

**Comment by TehNinth** [comment]
No. Spending any money on +1s before you have 7 +10s is a waste since you can get +10 for less than you pay for 10 +1s.

**Comment by Chdata** [comment]
Can't you just take Cost / Damage or Cost / Increase to find what the next best upgrade is?
