### ISSUE TITLE
Killswitch

### ISSUE THREAD

**Issue by nicatronTg** [wchill/steamSummerMinigame#243]
The script could really easily poll a website for a file containing a list of versions to automatically not execute, and display a warning requiring upgrade. Obviously this doesn't fix old scripts, but it would prevent people who start today from being stuck on 4.6.x forever.

**Comment by g1real** [comment]
Unfortunately it's impossible to interact from outside steamcommunity.com's domain. See also the eval() fiasco, and the fact the script already got a massive outrage for having such a vulnerability in it.

**Comment by phizch** [comment]
Actually, by using JSONP, it should be possible. It's designed to allow for cross site scripting after all..
http://json-p.org/
https://learn.jquery.com/ajax/working-with-jsonp/
I'm no expert, but I researched the problem earlier today. I was thinking of creating a CnC server program.

**Comment by gapple** [comment]
JSONP executes an external javascript directly, and from an untrusted source would be worse than a sanitized input to `eval()`.

From what I can tell, before the update codes was removed, it actually used `JSON.parse()` on some text extracted from a GET response, which wouldn't be susceptible to code injection.  Since it was loaded from the steamcommunity.com domain, there wasn't an issue with cross-domain requests.  There's just a stigma around the control code now, and it's not really that valuable.

The biggest issue is having a reliable and trusted source for hosting the information, that wouldn't end up crashing or blocking access due to high traffic.

----

If you're interested in learning more, [Cross-origin resource sharing](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) is a more modern and secure method than JSONP for loading cross-domain data.  Browser support wouldn't be an issue, since anyone running the script is using Chrome of Firefox, but it does require server support to send correct headers (which may be an issue with some CDNs).

**Comment by nicatronTg** [comment]
Honestly it doesn't have to be JSON, it could be literally anything (a csv,
perhaps) that doesn't require using Javascript to execute or parse it. Just
use string parsing and if statements.

**Comment by phizch** [comment]
@gapple, ah.. Yes, I see the problem.. jquery was designed so that a server couldn't inject a malicious function into the browser session.. JSONP seems to be back to the bad old days with eval.. A trusted server is definitely a must. 
Anyway, the CnC stuff I was tinkering with was a C# program that would handle the web serving itself, so sending the correct headers and message format wouldn't be a problem. Someone trusted with a static IP and open firewall port could host it.
I came to the conclusion myself that it probalby wouldn't add much, at least with some sensible anti ability spamming in the tampermonkey script. I was using the SteamDB version earlier and I had to disable some ability-use code. The Wchill version is much better in that regard, but I do miss the auto-buy functionality from the SDB version. :-)
