### ISSUE TITLE
"Skipped X levels in 5s" is showing double the actual number of levels

### ISSUE THREAD

**Issue by milkfat** [wchill/steamSummerMinigame#253]
Level jumps of 46K are showing up as 92K, 10K jumps are shown as 20K, etc.

I tried stepping through the logic, but I couldn't immediately identify the issue. Would it be simpler to store the last 5 level numbers in memory as opposed to the last 5 level_jumps? Then we could calculate the jump simply by subtracting the 5-ticks-ago level from the current level.

**Comment by g1real** [comment]
That was an approach I was thinking of but I couldn't be arsed figuring out how to program it. Currently however, it shows the last 5 jumps instead of the last 5 seconds. If it is somehow doubled something went wrong.

I'll try to change it around a bit tomorrow to give more useful, detailed info.

**Comment by armetilou** [comment]
I'm not sure how to check what the proposed fix was but this issue is a simple one: the function getLevelsSkipped() alters the array for no reason by moving the values in the 0, 1, 2 positions up one and adds them to a counter. This destroys the last value of the array and puts the first value in both the 0 and 1 positions. Then it adds the zero position again, doubling it in the total, which is why the skipped levels are about twice what they should be. The place where the function is called has no reason to alter the array like this since it's only supposed to return the sum of the last four level skips. It should probably be changed to something like

function getLevelsSkipped() {
	var total = 0;
	for (var i = 0; i < levelsSkipped.length-1; i++) {
		total += levelsSkipped[i];
	}
	total += levelsSkipped[0];
	return total;
}

While we're looking at the levelsSkipped code, in the main loop the for loop starts at i=4, which is two spots beyond where it should. The first iteration of the loop would be:
levelsSkipped[5] = levelsSkipped[4];
but 3 is the largest index of the array.

**Comment by armetilou** [comment]
Another note: calling the total displayed in the breadcrumbs the levels skipped in the last 5 seconds is a bit misleading. It's really the last 4 level jumps, no matter how long ago they occurred.

For the last five seconds there should probably be an array that stores the level number for each of the last 5 seconds and getLevelsSkipped() would just take the difference between the first and last.

**Comment by JimRaynor56** [comment]
I just added a commit to my pull request that makes it a bit less misleading.  Skipped level count would now drop to 0 if you sat in a fight for more than ~5 seconds. I can't guarantee that it updates exactly every second, but it seems fairly close to me.

**Comment by armetilou** [comment]
I think I see what the (old) code is supposed to be doing now. I'm not entirely sure, but I suspect it would be a lot easier just to keep an array of levels. The main loop would push the current level onto the array, n+1 elements to keep track of the last n seconds. Then getSkippedLevels would just take the difference between the first and last elements of the array to get the level skip count.

**Comment by g1real** [comment]
RIP skipped levels, you were never meant to be put on this world.
