### ISSUE TITLE
[Suggestion] On x100 levels, group players in non-boss Lanes so LN spam doesn't help trolls reset nuke cooldowns

### ISSUE THREAD

**Issue by meekmeekmeek** [wchill/steamSummerMinigame#265]
WH doesn't require that you be in a boss lane to benefit from the level skip.

LN however does require that you be in the lane with other LN users, so that you rest their WH cooldowns.

The downside of being in a boss lane is that using LN to reset WH cooldowns also resets the cooldowns on people's nukes, so (whether trolling or not) they can keep nuking the boss to death.

So if we have script users move to lane 1 whenever the x100 boss isn't in lane 1, and move to lane 2 whenever the x100 boss is in lane 1, then we could spam WH and LN forever in those lanes, without helping the nukers nuke the boss down prematurely.

This is nice because there's nothing the nukers can do about it - it depends on on the scripter's behaviour. There is a way trolls could still get their cooldowns reset, but it would slow them down a lot, and would be automatic if they're using a script.

One of us like a mod can manually go kill the boss if it's been up for a long time.

**Comment by MayeulC** [comment]
The idea is interesting. However, this would require some coordination between different scripts, such as steamdb's; and the spammers just have to go to the right lane one second to have their abilities reset (granted, if they are manual spammers, they probably won't think about it).

**Comment by meekmeekmeek** [comment]
True, but we are already pushing pretty hard to only have updated wchills users in the record groups.

This would get rid of manual/oblivious nukers, and make things annoying for intentional trolls, unless they write/mod their own scripts to automate swapping and nuking

**Comment by veniversum** [comment]
Trolls can just buy their own LNs to reset their nukes, and since they aren't buying any WHs, they can easily have >50k LNs. Then it is just a matter of pushing `"{"requested_abilities":[{"ability":27},{"ability":10}],"gameid":"xxx"}"` to the server every second.

Lane switching is not effective at dealing with nukers.

**Comment by owenleej** [comment]
This isn't a silver bullet but I think its a great idea and should help somewhat.

**Comment by meekmeekmeek** [comment]
At this point I doubt it's going to be implemented, but for the record, most of the reported trolls I've looked at today have tens of thousands of WHs, and very few if any LNs - the trolling is even parts using WH on the 99 levels as it is nuking on the 100s. So it would have worked fine on them, and forced them to leave game (and hence drop to a lower one) to change their purchases.

It looks like today's most promising game is miraculously free of trolls so we're good for today. Just gotta hope for the same luck tomorrow.

**Comment by MayeulC** [comment]
Looks merged. Would it allow us to upgrade elemental/turret, as we are no longer in the same lane as the boss ?

**Comment by Metalsand** [comment]
This is hilariously useless.  People do not NEED the script to play the game, and in fact, adding this to the code only gives players more incentive to skip the level beforehand since the game will throw those players in a non-boss room and avoid most of the gold gains while idling and being useless.

Anyone who thinks anti-trolling should be included in the code is no different from parents who try to ban violent video games;  adding anti-troll in the code does not do a goddamn thing because:

1.  The script isn't required to play the game.  At all.
2.  It takes minutes to remove it from the code.
3.  You can literally refresh your page right before you want to troll.
4.  It removes rewards from legitimate players since wormhole bosses give the most gold (since they are alive the longest)

Having anti-troll in the code only gives me more of a reason to wormhole PAST the boss, because I am forced to idle during wormhole bosses and do nothing.  It might be a script but I miss out on a ridiculous amount of gold so it's still an annoyance.

**Comment by wchill** [comment]
@Metalsand if you are using this script you should have enough gold anyway that it doesn't matter.

Regardless, it's already in the code. Closing.
