### ISSUE TITLE
Boss level issue

### ISSUE THREAD

**Issue by brahmamstr** [wchill/steamSummerMinigame#331]
The channel is not changing when is a boss level.

Probably a new update from steam.

Help us, please.

Edit: Happening every multiple of 100x. I noticed at 32200, and repeated at 32300, 32400....

**Comment by telekenetix** [comment]
This is not an issue. It is coded to do this on purpose to avoid helping the trolls.

**Comment by Metalsand** [comment]
I'm pretty sure if someone's trolling, they're not going to use a script to do so, especially given that most people using nukes on bosses do so because they don't know how to play.

Instead, the players who aren't working on serious ones get screwed because now I can neither contribute to a warp, nor can I get gold from the boss, given that the 100 level bosses drop the most.

There is no reason to put this in here.  If people want to nuke the boss, all they have to do is Refresh page to stop the script, and uh, nuke the boss.  It is absolutely and utterly ridiculous to keep it in there, because given that 100 level bosses stick around longer because of warps, I actually make more money using a simple mouse macro than this script, which goes to show how ridiculously inefficient the script has been made.

**Comment by Metalsand** [comment]
Also, it took me all of one minute to edit mine, so it's also completely worthless even at stopping trolls.  If I wanted to troll with it, I can take all of like 5 seconds to edit out the useless lane switcher.

**Comment by zjibben** [comment]
I think part of the goal is to allow as much time for wormhole use as possible, looking at

http://steamcommunity.com/sharedfiles/filedetails/?id=463162075

Relevant quote from the link:

"The script is designed so that, starting from boss wave 2000, every 100 bosses, abilities and clicking are disabled, meaning that the bosses take a long time to defeat. On these boss levels, the script will automatically deploy many wormholes while the boss slowly dies. (This is why you must not use abilities to kill them faster; it means fewer wormholes can be used simultaneously, as wormholes have an individual cooldown of 1 minute.)"

**Comment by brahmamstr** [comment]
I'll add a CSS switch to that feature in my code.
Thank you all.
