### ISSUE TITLE
If Spawner dies while Raining Gold, doesn't switch to spawn

### ISSUE THREAD

**Issue by BuddhaBuddy1** [wchill/steamSummerMinigame#56]
If someone nukes a Spawner while Raining Gold is active, nothing is clicked automatically, when it should start clicking on the spawn.

**Comment by oedw** [comment]
@BuddhaBuddy1 Does it still happen?

**Comment by BuddhaBuddy1** [comment]
It is hard to tell, the levels are over so fast, but I think it does still fail to switch to the spawn when the spawner dies while Raining Gold still has time left.

**Comment by wchill** [comment]
This merits some investigation

**Comment by armetilou** [comment]
I believe the problem is in the part where it has found a raining gold lane and is scanning through the enemies. The script scans through every monster in the game, as opposed to just the ones in the lane, and finds the one that would yield the most gold if it was in the raining gold lane.

What this means is that if there is a spawner in the lane with the highest raining gold multiplier it will attack the spawner. If there are only creeps but there is a spawner in a different lane, you will still be targeting the empty spawner position and wind up just sitting there.

**Comment by oedw** [comment]
@armetilou nice catch! Just submitted a pull request

**Comment by oedw** [comment]
@wchill https://github.com/wchill/steamSummerMinigame/pull/161

This can be closed :)
